/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    Checkout: {
      address: "0xEc49609ACd45092802EB576DC9Fc7AFa6b13853d",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "priceFeed_",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "maxPriceAgeSec_",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "AlreadyPaid",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidPrice",
          type: "error",
        },
        {
          inputs: [],
          name: "MemoTooLong",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
          ],
          name: "StalePrice",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "sent",
              type: "uint256",
            },
          ],
          name: "Underpaid",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "UnknownCheckout",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "merchant",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "usdCents",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "string",
              name: "memo",
              type: "string",
            },
          ],
          name: "CheckoutCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "payer",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "merchant",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "usdCents",
              type: "uint64",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "tinybarsPaid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "price",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "priceDecimals",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "priceUpdatedAt",
              type: "uint256",
            },
          ],
          name: "Paid",
          type: "event",
        },
        {
          inputs: [],
          name: "MAX_MEMO_BYTES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "checkoutCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "usdCents",
              type: "uint64",
            },
            {
              internalType: "string",
              name: "memo",
              type: "string",
            },
          ],
          name: "createCheckout",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "getCheckout",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "merchant",
                  type: "address",
                },
                {
                  internalType: "uint64",
                  name: "usdCents",
                  type: "uint64",
                },
                {
                  internalType: "enum Checkout.Status",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "payer",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "memo",
                  type: "string",
                },
              ],
              internalType: "struct Checkout.Order",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxPriceAgeSec",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "pay",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "priceFeed",
          outputs: [
            {
              internalType: "contract AggregatorV3Interface",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "quote",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint64",
              name: "usdCents",
              type: "uint64",
            },
            {
              internalType: "int256",
              name: "price",
              type: "int256",
            },
            {
              internalType: "uint8",
              name: "decimals",
              type: "uint8",
            },
          ],
          name: "requiredTinybars",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41214482,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
